import asyncio, os, yt_dlp
from typing import Union
from pyrogram.types import Message
from pyrogram.enums import MessageEntityType

# Cookies စာသားကို Code ထဲတွင် အသေထည့်ရန် (သင်ပြောသလို ပြင်ထားသည်)
MY_COOKIES_TEXT = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_PRIVACY_METADATA	CgJNTRIEGgAgZg%3D%3D
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXounGOWJraQeCKpqG-oSwq9wACgYKAZkSARISFQHGX2MizRsEjWIBfOf8FT3Y3LMa_RoVAUF8yKpOPp3cWUdYQ5Ao5O96IuJM0076
.youtube.com	TRUE	/	TRUE	1773283987	GPS	1
.youtube.com	TRUE	/	FALSE	1804818233	SIDCC	AKEyXzW1sqaKu6ScKuu9DKvRXkDOUkGb35L6HhIlYENKXlnQKqsd44MpPeDXCEVNXNiXMxq4
.youtube.com	TRUE	/	TRUE	1773368661	YSC	V5xhbUOi2aM
.youtube.com	TRUE	/	FALSE	1807842226	SID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXoYEH2e75zTffKW0Xjy7JjNAACgYKAYYSARISFQHGX2Miw6hqbohoy53Wf7whYiki9xoVAUF8yKqy6CRK8cS9icqdLlHz7eND0076
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-1PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	TRUE	1773282831	CONSISTENCY	AG2Tqf8zG-huG-xjZAla2JPHKiMEKIrXDCYwlOHHGuhn4BqYzEQeeWHU4KBqrAnF4gXzuExsDwlRUzVRXKDOoYbqs5Cc2zhXioJl1PDof9f5T3qYUl27a9fnzomuUSXtDrxnp1hPZjCN1LI5o2cd_BCb
.youtube.com	TRUE	/	TRUE	1807842226	SAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-1PSIDCC	AKEyXzWE3s3Z4jjWsZL2ADVxRV8QrrovXNLf3fLjfD9yjEGzPH3nS1nBe6mDRNa_Z19OZUfKZw
.youtube.com	TRUE	/	TRUE	1807842226	SSID	AT0hp-hXDaolbHwv7
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-1PSID	g.a0007gjBkEY2gKuIK-IDNA4O9IE8wiocn8xv3WOp-JbD6KKxZwXo1xo64CJRyhnVfADBa2PqOgACgYKAV0SARISFQHGX2Mi1ad7QdhlGEysEgNracH2bhoVAUF8yKreHDECH5KvXV8UNvE31fIb0076
.youtube.com	TRUE	/	TRUE	1807842226	__Secure-3PAPISID	ool8aM3EyPScJD-Y/A2ZqSKUfmKB11OwXW
.youtube.com	TRUE	/	TRUE	1804818233	__Secure-3PSIDCC	AKEyXzUDsCV5ZzeaZ8_RRuemevoTvbJutsmPMlGkA6CmKMPY1zz4f5-mKS5HuYiYODFDpNNRRg
.youtube.com	TRUE	/	TRUE	1804818226	__Secure-3PSIDTS	sidts-CjUBBj1CYnb_2un-x8U3DosdFcqPYVJhbg8Bk68ZCnIivIxZ-HGzJjNZhZ3mKsTTKPb9rfqcrxAA
.youtube.com	TRUE	/	TRUE	1788834187	__Secure-YNID	16.YT=GlwsbGn0fwwI-d-fno4xNR8ODUrXPmpXzVPd0Yw-YqCAZRTG2HLiCB6OPx_wu7cH-QOOa2ymy52RM-yS5A3yX2uA8Dp09uFhXKuV7krGSttP2UxmiC8yLsmvqa3Koezzs8cgbS5HZA8hQw6hVBJNPumr8rBZqjn0ehTKVK53mbtKU3iIf96Cquwc-hHR71SIqwN0TiSUPz3iQcwSl59oahyvxBQJrswqogCv1UEvAKwHWO9pQVvPhI7yj19BukJzfaYdJpxM8__eI0Ixp97WheNpkhT5n_qZm6xu_Go9dmMGTglnchyztzIzxRy0iS7SBky383yf7gUUuQTjcFvwCQ
.youtube.com	TRUE	/	FALSE	1807842226	APISID	r2h8dJdwnPtOnB6w/A696rI3lpsRhDG7gE
.youtube.com	TRUE	/	FALSE	1807842226	HSID	AKFaV2VhVw1F0A1Ki
.youtube.com	TRUE	/	TRUE	1807842227	LOGIN_INFO	AFmmF2swRAIgcB7wcOs4WNVu-ntf7mqpZ0eDodNht4tOYj9GjX_22kcCIDZ6go5sU7AJYiXaiXvDo7RTNDux2DRqDwi5aMYf_6dA:QUQ3MjNmd2RNVmZwS2M4ajJCX0NDQTZRLUhZUERGOVU3ekR3UWpkZVZ3QXVwZ1JEWmM5cDExQWV4MzRzaXF5bS1uY0dFTUlDcDJySkVkd3pZbFRVc29uSEtKT0tscDRDOG93c3Zxd0R1ZkZCTlBYcGdqaFVzMWhhOTZaRWlwTDF6WDJWU0tiM3FmRW05dUlkMlVndFROblhyejBxeGc2a09R
.youtube.com	TRUE	/	TRUE	1807842230	PREF	tz=Asia.Rangoon&f7=100&f4=4000000
.youtube.com	TRUE	/	TRUE	1788834227	VISITOR_INFO1_LIVE	rQRaTxG5Dg8
"""

class YouTubeAPI:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="

    # --- Error တက်နေတဲ့ url method ကို ဒီမှာ ပြန်ထည့်ထားပါတယ် ---
    async def url(self, message_1: Message) -> Union[str, None]:
        messages = [message_1]
        if message_1.reply_to_message:
            messages.append(message_1.reply_to_message)
        for message in messages:
            if message.entities:
                for entity in message.entities:
                    if entity.type == MessageEntityType.URL:
                        return (message.text or message.caption)[entity.offset : entity.offset + entity.length]
            elif message.caption_entities:
                for entity in message.caption_entities:
                    if entity.type == MessageEntityType.TEXT_LINK:
                        return entity.url
        return None

    # --- Download method (API မလိုတော့ဘဲ Cookies နဲ့ တိုက်ရိုက်ဒေါင်းမည်) ---
    async def download(self, link, mystic, video=None, **kwargs) -> str:
        cookie_path = "cookies_temp.txt"
        with open(cookie_path, "w") as f:
            f.write(MY_COOKIES_TEXT)

        loop = asyncio.get_running_loop()
        def direct_download():
            ydl_opts = {
                "format": "bestvideo+bestaudio/best" if video else "bestaudio/best",
                "outtmpl": "downloads/%(id)s.%(ext)s",
                "cookiefile": cookie_path,
                "quiet": True,
            }
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(link, download=True)
                return os.path.join("downloads", f"{info['id']}.{info['ext']}")

        try:
            downloaded_file = await loop.run_in_executor(None, direct_download)
            return downloaded_file, False
        except Exception as e:
            print(f"Download Error: {e}")
            return None, False
        finally:
            if os.path.exists(cookie_path):
                os.remove(cookie_path)
